# Generated by Django 3.1.1 on 2020-10-11 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=256)),
                ('gender', models.CharField(blank=True, max_length=256)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('phn_number', models.CharField(blank=True, max_length=20)),
                ('facebook', models.URLField(blank=True)),
                ('address', models.TextField(blank=True, max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=256)),
                ('item_name', models.CharField(blank=True, max_length=256)),
                ('num_of_item', models.IntegerField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('donar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_d', to='account_app.userprofile')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
